import re
import networkx as nx
from networkx.algorithms.community import louvain_communities
import sys
import os
lib_path=".."
sys.path.append(lib_path)
from tools.fileOperation import *
import argparse
final_map={} # call graph, but ignoring cases where a function is called multiple times within another function
direct_map={}
indirect_map={}
indirectcallsite_map={}
directcallsite_map={}
ToInsertFunc=set()
visited=set()
AvoidFuncSet=set()
recursive_func=set()
checkpoint_callsite=set()
leaf_func=set() ## leaf functions, i.e., functions that do not call other functions
edge_count=0
final_map_no_cycle={} ## call relationships after removing cycles from the subgraph
final_sub_map={} ## calling subgraph obtained with key operations as root nodes, but ignoring cases where a function is called multiple times within another function
IgnoreFuncSet=set()
D = nx.DiGraph()
E=nx.DiGraph()

def is_ignored_func(func_name):
    global AvoidFuncSet
    global IgnoreFuncSet
    return func_name in AvoidFuncSet or func_name in IgnoreFuncSet
## Generate indirect calls based on the final results of svf; a more accurate result has already been generated by combining meta_data and svf.
def initialize_Ind_map(indirect_target_map_file):
    global final_map
    global indirect_map
    global indirectcallsite_map
    IRCallsite_pattern=re.compile(r"In function\s*:\s*([^\s]+)\s*indirect callsite\s*:\s*(.*)")
    target_pattern=re.compile(r'--target\s*(\S+)')
    IndirectCallsiteFunc=None
    with open(indirect_target_map_file,'r') as file:
        for line  in file:
            line= line.strip()
            IRcallsite_match=IRCallsite_pattern.match(line)
            target_match=target_pattern.match(line)
            if IRcallsite_match:
                IndirectCallsiteFunc=IRcallsite_match.group(1)
                Indirectcallsite=IRcallsite_match.group(2)
                if IndirectCallsiteFunc not in final_map:
                    final_map[IndirectCallsiteFunc]=set()
                if IndirectCallsiteFunc not in indirect_map:
                    indirect_map[IndirectCallsiteFunc]=set()
                if Indirectcallsite not in indirectcallsite_map:
                    indirectcallsite_map["ind-"+Indirectcallsite]=set()
            elif target_match:
                if target_match:
                    target_function=target_match.group(1)
                    if target_function not in final_map:
                        final_map[target_function]=set()
                    final_map[IndirectCallsiteFunc].add(target_function)
                    indirect_map[IndirectCallsiteFunc].add(target_function)
                    indirectcallsite_map["ind-"+Indirectcallsite].add(target_function)

def initialize_di_map(direct_target_map_file): ## Establish the mapping relationship between call sites and call targets for direct calls
    global final_map
    global direct_map
    global directcallsite_map
    IRCallsite_pattern=re.compile(r"In function\s*:\s*([^\s]+)\s*direct callsite\s*:\s*(.*)")
    target_pattern=re.compile(r'--target\s*(\S+)')
    directCallsiteFunc=None
    with open(direct_target_map_file,'r') as file:
        for line  in file:
            line= line.strip()
            IRcallsite_match=IRCallsite_pattern.match(line)
            target_match=target_pattern.match(line)
            if IRcallsite_match:
                directCallsiteFunc=IRcallsite_match.group(1)
                directCallsite=IRcallsite_match.group(2)
                if directCallsiteFunc not in final_map:
                    final_map[directCallsiteFunc]=set()
                if directCallsiteFunc not in direct_map:
                    direct_map[directCallsiteFunc]=set()
                if directCallsite not in directcallsite_map:
                    directcallsite_map["di-"+directCallsite]=set()
            elif target_match:
                if target_match:
                    target_function=target_match.group(1)
                    if target_function not in final_map:
                        final_map[target_function]=set()
                    final_map[directCallsiteFunc].add(target_function)
                    direct_map[directCallsiteFunc].add(target_function)
                    directcallsite_map["di-"+directCallsite].add(target_function)
    # for target in direct_map["_ZNK7AP_AHRS17get_filter_statusER17nav_filter_status"]:
    #     print("debug -----------"+target+'\n')


def dfs_visit(start_node,visited):
    global ToInsertFunc
    global final_map
    global AvoidFuncSet
    global D
    global indirect_map
    global direct_map
    global final_sub_map
    global checkpoint_callsite
    global edge_count
    #print(start_node)
    if is_ignored_func(start_node):
        return
    if start_node not in final_map:
        return
    if start_node not in final_sub_map:
        final_sub_map[start_node]=set()
    if start_node in visited: 
        return
    if start_node not in visited:
        ToInsertFunc.add(start_node)
        visited.add(start_node)
        if not D.has_node(start_node):
            D.add_node(start_node)
        for callee_node in final_map[start_node]:
            if not is_ignored_func(callee_node):
                edge_count=edge_count+1
                #ToInsertFunc.add(callee_node)
                final_sub_map[start_node].add(callee_node)
                if not D.has_node(callee_node):
                    D.add_node(callee_node)
                if not D.has_edge(start_node,callee_node):
                    if start_node in indirect_map and callee_node in indirect_map[start_node]:
                        D.add_edge(start_node,callee_node,color='red')
                    if start_node in direct_map and callee_node in direct_map[start_node]:
                        D.add_edge(start_node,callee_node,color='black')
                dfs_visit(callee_node,visited)

def find_only_oncefunc():
    """
    Find functions that are called only once, and find leaf nodes.
    """
    global final_map
    global AvoidFuncSet
    global directcallsite_map
    global indirectcallsite_map
    global final_sub_map
    global ToInsertFunc
    global leaf_func
    func_called_map={} # record call sites of functions that are called only once
    func_called_count={} # record the number of times each function is called
    for key ,values in directcallsite_map.items():
        for value in values:
            if value not in func_called_count:
                func_called_count[value]=1
            else:
                func_called_count[value]+=1
    for key ,values in indirectcallsite_map.items():
        for value in values:
            if value not in func_called_count:
                func_called_count[value]=1
            else:
                func_called_count[value]+=1
    for key,value in func_called_count.items(): # key represents the called function, value represents the call count
        find_callsite=False
        if value >1:
            continue
        else :
            for key1,values1 in directcallsite_map.items(): # key1 represents the call site, values1 represents the set of called functions
                for value1 in values1:
                    if value1==key:
                        func_called_map[key]=key1
                        find_callsite=True
                        break
            # if find_callsite==True:
            #     continue
            for key2,values2 in indirectcallsite_map.items():
                for value2 in values2:
                    if value2==key:
                        func_called_map[key]=key2
    file="../output/only_called_once_func.txt"
    with open(file,"w") as f:
        for key ,value in func_called_map.items():
            if key in ToInsertFunc :
                f.write(key+"-"+value+'\n')
    # file1="../output/leaf_func.txt" ## stores leaf functions, i.e., functions that do not call other functions; checkpoints are inserted at the beginning of these functions
    # with open(file1,"w") as f:
    for callsite ,targets  in final_sub_map.items():
        if len(targets)==0: 
            leaf_func.add(callsite)
            #f.write(callsite+'\n')
    print("Leaf function size is :"+str(len(leaf_func)))
"""
Assign a weight to each edge.
Weight definition:
    Traverse from a certain function node; if it can return to itself, then the weights of all points on this path are incremented by 1, and recursion stops.
Algorithm description:
    1. Perform deep-first search on each node; if it can return to itself, the weights of all points on this path are incremented by 1 and execution stops.
    2. If a previously visited node is encountered, return.
    3. If an unvisited node is encountered, add the node to the visited set, and then perform deep-first traversal on all its child nodes.
"""
def dfs_count_node(root_node,start_node,visited=None,node_list=None,path_list=None,path_list_sorted=None):
    global final_map_no_cycle
    global AvoidFuncSet
    result=False
    if start_node in visited:
        result=False
    if start_node not in visited:
        visited.add(start_node)
        for callee_node in final_map_no_cycle[start_node]:
            if not is_ignored_func(callee_node):
                if callee_node == root_node:
                    node_list.append(start_node)
                    # Sort node_list and deduplicate paths
                    node_list_sorted=sorted(node_list)
                    path_list.add(node_list)
                    path_list_sorted.add(node_list_sorted)
                    # for node in node_list:
                    #     node_weight[node]=node_weight.get(node,0)+1
                    # node_weight[start_node]=node_weight.get(start_node,0)+1
                    result=True
                    return result
                else:
                    node_list.append(start_node)
                    result=dfs_count_node(root_node,callee_node,visited,node_list,path_list)
                    node_list.pop()
                    if result==True:
                        return result
            else:
                continue
    return result
# calculate from each node
def count_node():
    global final_sub_map
    global AvoidFuncSet
    path_list=set()
    path_list_sorted=set()
    for key  in final_sub_map.keys():
        visited=set()
        node_list=[]
        dfs_count_node(key,key,visited,node_list,path_list,path_list_sorted)
    return path_list,path_list_sorted
"""
Determine if there are cycles in final_map_no_cycle.
Determination method: Start from a node in the graph; if it can return to itself, it indicates a cycle.
"""
def judge_cycle(root_node,start_node,visited=None):
    global AvoidFuncSet
    global final_map_no_cycle
    result=False
    if start_node in visited: 
        result= False
    if start_node not in visited:
        visited.add(start_node)
        for callee_node in final_map_no_cycle[start_node]:
            if not is_ignored_func(callee_node):
                if callee_node == root_node:
                    result= True
                    return result
                else:
                    result=judge_cycle(root_node,callee_node,visited)
                    if result==True:
                        return result
            else:
                continue
    return result
"""
Break a cycle and generate a new graph.
Algorithm description:
    1. First, generate a networkx directed graph based on the calling subgraph.
    2. Use nx.simple_cycles(E) to find all cycles.
    3. Calculate how many cycles each point appears in; this is the point's weight.
    4. Find the edge max_node with the most occurrences (highest weight), delete the point, and decrement the weight of related points in node_weight.
    5. Determine if there are cycles; if none, exit.
    6. If cycles exist, repeat steps 4-5.

"""
def break_cycle():
    global final_sub_map
    global final_map_no_cycle
    global AvoidFuncSet
    global recursive_func
    global E
    global ToInsertFunc
    final_map_no_cycle=final_sub_map.copy()
    # Generate a new graph
    for key,value in final_map_no_cycle.items():
        if not E.has_node(key):
            E.add_node(key)
        for callee_node in value:
            if not is_ignored_func(callee_node):
                if not E.has_node(callee_node):
                    E.add_node(callee_node)
                if not E.has_edge(key,callee_node):
                    E.add_edge(key,callee_node)
    cycles=list(nx.simple_cycles(E))
    node_weight={}
    for cycle in cycles: ## calculate the count for each edge
        for i in range(len(cycle)):
            node_weight[cycle[i]]=node_weight.get(cycle[i],0)+1

    while True:
        # #original code without networkx
        # # This scheme is used only when the subgraph is too large because networkx may fail to find all cycles. In such cases, weights are assigned to edges based on whether a node can return to itself.
        # # Find some cycles (not all) by checking if a node can return to itself, deduplicate the cycles (remove lists containing the same nodes, ignoring order), and then calculate the weight of each node (how many cycles each point appears in).
        # # Find the point with the highest weight, then delete it and the edges starting from it.
        # # Recalculate weights until there are no cycles in the graph.
        # if nx.is_directed_acyclic_graph(E): # determine if there are cycles in the graph, true means no cycles
        #     break
        # node_weight_backup={}
        # path_list,path_list_sorted=count_node()
        # max_weight=0
        # for path in path_list_sorted: # Calculate weights; in fact, it's counting the occurrences of each point.
        #     for node in path:
        #         node_weight_backup[node]=node_weight.get(node,0)+1
        # for key,value in node_weight_backup.items(): # find the point with the highest weight
        #     if value>max_weight:
        #         max_weight=value
        #         max_node=key
        # tmp_node=set()
        # for path in path_list: # find the edge starting with max_node in the cycle and delete it
        #     for i in range(len(path)):
        #         if path[i]==max_node and i!=len(path)-1: ## find the edge to delete
        #             tmp_node.add(path[i+1])
        #         if path[i]==max_node and i==len(path)-1: # find the edge to delete
        #             tmp_node.add(path[0])
        # for node in tmp_node:
        #     final_map_no_cycle[max_node].remove(node)
        #     E.remove_edge(max_node,node) # delete the edge
        # recursive_func.add(max_node)
#-------------------------------------------------------------------------------------------------
        # Use networkx library
        if nx.is_directed_acyclic_graph(E): # determine if there are cycles in the graph, true means no cycles
            break
        max_weight=0
        max_node=None
        for key,value in node_weight.items():
            if value>max_weight:
                max_weight=value
                max_node=key
        recursive_func.add(max_node) # add the current function to recursive functions
        #print(max_edge)
        # Delete all cycles containing delete_node, delete cycles containing edges starting with delete_node, and adjust the weights of other edges in the cycles
        delete_node=max_node
        node_weight[delete_node]=0 # delete the weight of this edge
        #tmp_cycles=set()
        tmp_cycles = []
        to_remove_edge=set()
        for cycle in cycles:
            result=False
            for i in range(len(cycle)):
                if cycle[i]==delete_node:
                    # tmp_cycles.add(cycle)
                    tmp_cycles.append(cycle)
                    result=True
                    break
            if result==True:
                for i in range(len(cycle)):
                    if cycle[i]!=delete_node: # decrement the weight of nodes in the cycle that are not delete_node
                        node_weight[cycle[i]]=node_weight.get(cycle[i],0)-1
                    elif cycle[i]==delete_node: # if it is an edge from delete_node, mark it for deletion
                        node_weight[cycle[i]]=0
                        if i==len(cycle)-1:
                            to_remove_edge.add((cycle[-1],cycle[0]))
                        else:
                            to_remove_edge.add((cycle[i],cycle[i+1]))
        for edge in to_remove_edge:
            E.remove_edge(edge[0],edge[1])
            final_map_no_cycle[edge[0]].remove(edge[1])
        # delete the cycle containing delete_node
        print(tmp_cycles[0])
        for cycle in tmp_cycles:
            cycles.remove(cycle)
        



    
"""
Determine if there are cycles in final_map_no_cycle.
Determination method: Start from a node in the graph; if it can return to itself, it indicates a cycle.
If yes, return True
If no, return False
"""
def judge_cycle_in_copy_disable(root_node,start_node,visited=None):
    global final_map_no_cycle
    global AvoidFuncSet
    result=False
    if start_node in visited: 
        result= False
    if start_node not in visited:
        visited.add(start_node)
        for callee_node in final_map_no_cycle[start_node]:
            if not is_ignored_func(callee_node):
                #print(callee_node)
                if callee_node == root_node:
                    result= True
                    return result
                else:
                    result=judge_cycle_in_copy_disable(root_node,callee_node,visited)
                    if result==True:
                        return result
            else:
                continue
    return result
def judge_cycle_disable(root_node,start_node,depth=1,visited=None):
    """
    Determine if there are cycles.
    First determine if there are cycles in final_map_no_cycle.
    If no cycles, exit and return False.
    If cycles exist, perform depth-first search, delete edges in the cycles (edges that can return to root_node from root_node), and return True.
    """
    global final_sub_map
    global AvoidFuncSet
    global final_map_no_cycle
    global recursive_func
    result=False
    if depth==1: # first determine if there is a cycle based on the current root_node's call relationships in final_map_no_cycle, i.e., whether this cycle has been processed before
        visited1=set()
        if judge_cycle_in_copy_disable(root_node,start_node,visited1)==False:
            return False
    if start_node in visited: 
        return False
    if start_node not in visited:
        visited.add(start_node)
        for callee_node in final_sub_map[start_node]: ## find all call relationships in final_sub_map
            if not is_ignored_func(callee_node):
                #print(callee_node)
                if callee_node == root_node:
                    #print(previous_node)
                    recursive_func.add(start_node)
                    final_map_no_cycle[start_node].remove(root_node) # remove the edge that can return to root_node
                    result= True
                    print(result)
                    return result
                else :
                    result=judge_cycle_disable(root_node,callee_node,depth+1,visited)
                    if result==True:
                        return result

    return result
"""
Break a cycle and generate a new graph.
Algorithm description:
    1. Traverse the graph according to the keys of final_sub_map.
    2. If in the graph, you can reach the key node starting from it, delete the edge reaching the key node in the path.
    3. Repeat steps 1-2 until there are no cycles starting from key.
Algorithm disadvantages:
    This algorithm is affected by the traversal order. Different traversal orders may lead to different results, and potentially suboptimal ones, such as deleting more edges than necessary.
"""
def break_cycle_disable():
    global final_sub_map
    global final_map_no_cycle
    global AvoidFuncSet
    global recursive_func
    global E

    #use to debug
    # final_map_no_cycle=final_sub_map.copy()
    # visited=set()
    # root_node="_ZN17AP_Logger_Backend15find_oldest_logEv"
    # result=judge_cycle_disable(root_node,root_node,1,visited)
    # print(result)
    final_map_no_cycle=final_sub_map.copy()
    for key  in final_sub_map.keys():
        while True:
            visited=set()
            result=judge_cycle_disable(key,key,1,visited)
            print(str(result)+"  "+key)
            if result==False:
                break
    for value in recursive_func: # at this point, it is actually calling the function preceding root_node
        print("In function :"+value)
        # for key in final_map_no_cycle[value]:
        #     print(key)
    # Generate a new graph
    for key,value in final_map_no_cycle.items():
        if not E.has_node(key):
            E.add_node(key)
        for callee_node in value:
            if not is_ignored_func(callee_node):
                if not E.has_node(callee_node):
                    E.add_node(callee_node)
                if not E.has_edge(key,callee_node):
                    E.add_edge(key,callee_node)
    # for testing
    # for key in final_map_no_cycle[root_node]:
    #     print(key)

# This version of get_checkpoint_callsite generates 26 checkpoint_callsites for the update_xy_controller operation, but it generates 4000 hash values, which is too large.
# def get_checkpoint_callsite(root_node,func_path_lenth=5,func_numbuer=16):
#     global E
#     global checkpoint_callsite
#     global leaf_func
#     path_length_map={}
#     undirected_E = E.to_undirected()
#     node_depth_map={} # minimum depth from leaf nodes to root node
#     for func in leaf_func:
#         if func not in undirected_E:
#             continue
#         # calculate the minimum depth from func to the root node
#         try:
#             depth = nx.shortest_path_length(E, source=root_node, target=func)
#             node_depth_map[func]=depth
#         except nx.NetworkXNoPath:
#             node_depth_map[func]=sys.maxsize
    # find the minimum distance between any two points in leaf_func within undirected_E, sorting by node_depth_map in ascending order
#     sorted_leaf_func = sorted(leaf_func, key=lambda x: node_depth_map.get(x, sys.maxsize))
#     for func in sorted_leaf_func:
#         print(f"leaf_func: {func}, depth: {node_depth_map.get(func, 'N/A')}")
#         if func not in undirected_E:
#             continue
#         less_three=False
#         for target in leaf_func:
#             if target==func or target not in undirected_E:
#                 continue
#             distance = nx.shortest_path_length(undirected_E, source=func, target=target)
#             print(f"Distance from {func} to {target}: {distance}")
#             if distance <func_path_lenth :
#                 less_three=True
#                 #checkpoint_callsite.add(func)
#                 #checkpoint_callsite.add(target)
#                 break
#         if less_three==False:
#             checkpoint_callsite.add(func)
#             #checkpoint_callsite.add(target)
# the following get_checkpoint_callsite version has randomness, possibly generating 46, 45, or even 44 checkpoint_callsites for the update_xy_controller operation.
def get_checkpoint_callsite(root_node,func_path_lenth=4,func_numbuer=16):
    global E
    global checkpoint_callsite
    global leaf_func
    path_length_map={}
    undirected_E = E.to_undirected()
    node_depth_map={} # minimum depth from leaf nodes to root node
    for func in leaf_func:
        if func not in undirected_E:
            continue
        # calculate the minimum depth from func to the root node
        try:
            depth = nx.shortest_path_length(E, source=root_node, target=func)
            node_depth_map[func]=depth
        except nx.NetworkXNoPath:
            node_depth_map[func]=sys.maxsize
    # Find the minimum distance between any two points in leaf_func in undirected_E, sorted by node_depth_map from smallest to largest to generate 46, or from largest to smallest to generate 45. Ascending order should be used because it processes shorter depths first, resulting in smaller evidence.
    sorted_leaf_func = sorted(leaf_func, key=lambda x: node_depth_map.get(x, sys.maxsize))
    for func in sorted_leaf_func:
        print(f"leaf_func: {func}, depth: {node_depth_map.get(func, 'N/A')}")
        if func not in undirected_E:
            continue
        for target in leaf_func:
            if target==func or target not in undirected_E:
                continue
            if (func,target) in path_length_map or (target,func) in path_length_map:
                continue
            # First determine if there is a path between func and target to avoid NetworkXNoPath exception
            if not nx.has_path(undirected_E, func, target):
                continue
            distance = nx.shortest_path_length(undirected_E, source=func, target=target)
            path_length_map[(func,target)]=distance
            path_length_map[(target,func)]=distance
            print(f"Distance from {func} to {target}: {distance}")
            #if distance == func_path_lenth : # modified for sglib-combined
            if distance == func_path_lenth : #for ardupilot
                checkpoint_callsite.add(func)
                break

def main():
    # indirect_file="../../virtualcall/output/indirectcall.txt"
    # indirect_file="../output/static_final_result.txt"
    # direct_file="../../virtualcall/output/direct_call_result.txt"
    # ToInsertFuncFile="../output/ToInsertFunc.txt"
    # avoid_handle_function="../../../ardupilot/build/SITL_arm_linux_gnueabihf/avoid_handle_function.txt"
    # mainjob_file_path="../../../ardupilot/build/SITL_arm_linux_gnueabihf/path_start.txt"
    # recursive_func_file="../output/recursive_header_func.txt"
    parser = argparse.ArgumentParser(description="Static analysis for function call graphs.")
    parser.add_argument('--indirect_file', type=str, default="../../virtualcall/output/indirectcall.txt", help='Path to indirect call file')
    parser.add_argument('--direct_file', type=str,  default="../../virtualcall/output/direct_call_result.txt", help='Path to direct call file')
    parser.add_argument('--ToInsertFuncFile', type=str, default="../output/ToInsertFunc.txt", help='Path to output ToInsertFunc file')
    parser.add_argument('--avoid_handle_function', type=str, default="../../../ardupilot/build/SITL_arm_linux_gnueabihf/avoid_handle_function.txt", help='Path to avoid handle function file')
    parser.add_argument('--ignore_func', type=str, action='append', default=[], help='Function name to ignore during DFS. Can be used multiple times, e.g. --ignore_func foo --ignore_func bar')
    parser.add_argument('--ignore_func_file', type=str, default=None, help='Path to a file containing function names to ignore (one function name per line)')
    parser.add_argument('--mainjob_file_path', type=str, default="../../../ardupilot/build/SITL_arm_linux_gnueabihf/critical_function.txt", help='Path to main job file')
    parser.add_argument('--recursive_func_file', type=str, default="../output/recursive_header_func.txt", help='Path to output recursive function file')
    args = parser.parse_args()

    indirect_file = args.indirect_file
    direct_file = args.direct_file
    ToInsertFuncFile = args.ToInsertFuncFile
    avoid_handle_function = args.avoid_handle_function
    ignore_func_file = args.ignore_func_file
    mainjob_file_path = args.mainjob_file_path
    recursive_func_file = args.recursive_func_file
    # checkpoint_func_file="../../../ardupilot/build/SITL_arm_linux_gnueabihf/"
    global ToInsertFunc
    global D
    global E
    global recursive_func
    global AvoidFuncSet
    global IgnoreFuncSet
    global checkpoint_callsite
    # global checkpoint_func
    init_set(avoid_handle_function,AvoidFuncSet)
    for func in args.ignore_func:
        for item in func.split(','):
            item = item.strip()
            if item:
                IgnoreFuncSet.add(item)
    if ignore_func_file:
        init_set(ignore_func_file,IgnoreFuncSet)
    print("Ignore function size is :"+str(len(IgnoreFuncSet)))
    # init_set(checkpoint_func_file,checkpoint_func)
    initialize_Ind_map(indirect_file)
    initialize_di_map(direct_file)

    final_file="../output/call_graph.txt"
    global final_map
    critical_operation_set=set() ## critical operation set
    with open(mainjob_file_path,"r") as file:
        for line in file:
            start_node_name=line.strip()
            visited=set()
            #print("node list:", list(graph.nodes))
            #start_node="Node0x560e91943230" ## for testing only
            print("start node is :"+start_node_name)
            critical_operation_set.add(start_node_name)
            dfs_visit(start_node_name,visited)
    file.close()   
 
    
    #dfs_visit("_ZN13AC_PosControl20update_xy_controllerEv",visited)
    global final_sub_map
    print("Number of keys in final_sub_map:", len(final_sub_map))
    break_cycle()
    #break_cycle("_ZN10AP_RAMTRON4readEjPhj")
    #break_cycle("_ZN6Copter18update_flight_modeEv")
    with open(ToInsertFuncFile,'w') as file:
        for func in ToInsertFunc:
            file.write(func+'\n')
    file.close()
    with open(final_file,'w') as file:
        for callsite,targets in final_map.items():
            functionName=callsite
            file.write("In function :"+functionName+'\n')
            for target in targets:
                file.write("--target  "+target+'\n')
    file.close()
    with open(recursive_func_file,'w') as file:
        for func in recursive_func:
            file.write(func+'\n')
    nx.nx_agraph.write_dot(D,"../output/final_sub_call_graph.dot")
    nx.nx_agraph.write_dot(E,"../output/final_sub_call_graph_nocycle.dot")
    find_only_oncefunc()
    for critical_operation in critical_operation_set:
        #get_checkpoint_callsite(critical_operation,func_path_lenth=5,func_numbuer=16)#for sglib-combined
        get_checkpoint_callsite(critical_operation,func_path_lenth=2,func_numbuer=16)#for ardupilot 
        #get_checkpoint_callsite(critical_operation,func_path_lenth=5,func_numbuer=16)#for rc-cb
        #get_checkpoint_callsite(critical_operation,func_path_lenth=3,func_numbuer=16)#for house alarm
        #get_checkpoint_callsite(critical_operation,func_path_lenth=0,func_numbuer=16)#only loop and recursive for px4
    for node in checkpoint_callsite:
        print("checkpoint callsite: "+node)
    print("checkpoint size is :" +str(len(checkpoint_callsite)))
    file1="../output/leaf_func.txt" ## stores leaf functions, i.e., functions that do not call other functions; checkpoints are inserted at the beginning of these functions
    with open(file1,"w") as f:
        for func in checkpoint_callsite:
        #for func in leaf_func: #for copter attack
            f.write(func+'\n')
    f.close()
if __name__ == '__main__':
    main()
