export PREFIX="$HOME/llvm-arm-cross/llvm-project-16.0.0/build/" 
export CC="$PREFIX/bin/clang"
export PI3_FLAGS="--target=arm-linux-gnueabihf -mcpu=cortex-a53 -mfpu=vfpv4 -mfloat-abi=hard -mno-unaligned-access -fno-strict-aliasing"
export CFLAGS="-O0 -flto -Xclang -no-opaque-pointers --target=arm-linux-gnueabihf -gdwarf-4 -flto -fno-discard-value-names -fembed-bitcode -fno-exceptions -fno-jump-tables"
export CXX="$PREFIX/bin/clang++"
export CXXFLAGS="-O0 -flto -Xclang  -no-opaque-pointers --target=arm-linux-gnueabihf -gdwarf-4 -flto -fno-discard-value-names -fembed-bitcode -fwhole-program-vtables -fno-exceptions  -fno-jump-tables "
export AR="$PREFIX/bin/llvm-ar"
export LD="$PREFIX/bin/lld"
export NM="$PREFIX/bin/nm"
export RANLIB="$PREFIX/bin/llvm-ranlib"
export LDFLAGS="-fuse-ld=lld -flto -devirt"