#!/bin/bash
CURRENT_DIR=$(pwd)
ROOT_DIR="${CURRENT_DIR}/.."
echo "Current directory is: $CURRENT_DIR"
TOOLCHAIN_DIR="${ROOT_DIR}/toolchains/aarch32"
echo "Generating offline evidence"
cd ../pre-analysis16.0/util/generate_final_hash/ || { echo "Failed to enter generate_final_hash directory"; exit 1; }
echo "Generating configuration file"
rm -f ../output/hash_database_single_on_server_px4.txt
python3 gen_config.py ../output/px4_output.S --binary-file ../output/px4_output --program-header px4_output.ph -o ../output/replay_single.cfg
echo "Re-executing database generation"
echo "-o: Target file"
echo "-c: Configuration file generated by gen_config.py"
echo "-bf: Binary file to be analyzed"
#python3 generate_offline_database_no_threshold.py  -c ../output/replay_single.cfg -l -o ../output/hash_database_single_on_server_px4.txt -bf ../output/px4_output -dis ../output/px4_output.S ../output/px4_output  -v -v -v
python3 generate_offline_database_no_threshold.py \
  -c ../output/replay_single.cfg \
  -l \
  -o ../output/hash_database_single_on_server_px4.txt \
  -bf ../output/px4_output \
  -dis ../output/px4_output.S \
  -IR ../output/after_insert_dummy_px4.ll \
  -svf ../../virtualcall/output/indirectcall_px4.txt \
  -tiff ../output/ToInsertFunc_px4.txt \
  -ocof ../output/only_called_once_func_backup_px4.txt \
  ../output/px4_output \
  -v -v -v
echo "Filtering out duplicate hash values"
python3 ReWriteDataBase.py -i ../output/hash_database_single_on_server_px4.txt  -o ../output/final_hash_database_single_on_server_px4.txt -eo ../output/hash_edges_map_px4.txt