#!/bin/bash
CURRENT_DIR=$(pwd)
ROOT_DIR="${CURRENT_DIR}/.."
echo "Current directory is: $CURRENT_DIR"
TOOLCHAIN_DIR="${ROOT_DIR}/toolchains/aarch32"
echo "Generate offline evidence"
cd ../pre-analysis16.0/util/generate_final_hash/ || { echo "Failed to enter generate_final_hash directory"; exit 1; }
echo "Generate configuration file"
rm -f ../output/hash_database_single_on_server_"$1".txt
python3 gen_config.py ../output/"$1"_output.S --binary-file ../output/"$1"_output --program-header "$1".ph -o ../output/replay_single.cfg
echo "Re-execution to generate database"
echo "-o: target file"
echo "-c: configuration file generated by gen_config.py"
echo "-bf: the final binary file to be analyzed"


python3 generate_offline_database_no_threshold.py  -c ../output/replay_single.cfg -l -o ../output/hash_database_single_on_server_"$1".txt -bf ../output/"$1"_output -dis ../output/"$1"_output.S ../output/"$1"_output  -v -v -v

python3 generate_offline_database_no_threshold.py \
  -c ../output/replay_single.cfg \
  -l \
  -o ../output/hash_database_single_on_server_"$1".txt \
  -bf ../output/"$1"_output \
  -dis ../output/"$1"_output.S \
  -IR ../output/after_insert_dummy_"$1".ll \
  -svf ../../virtualcall/output/indirectcall_"$1".txt \
  -tiff ../output/ToInsertFunc_"$1".txt \
  -ocof ../output/only_called_once_func_backup_"$1".txt \
  ../output/"$1"_output \
  -v -v -v

echo "Filter out duplicate hash values"
python3 ReWriteDataBase.py -i ../output/hash_database_single_on_server_"$1".txt -o ../output/final_hash_database_single_on_server_"$1".txt