#!/bin/bash
CURRENT_DIR=$(pwd)
ROOT_DIR="${CURRENT_DIR}/.."
echo "Set LLVM related paths"
LLVM_OPT="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/bin/opt"
LLVM_DIS="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/bin/llvm-dis"
LLVM_CHECKPOINT_PASS="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/lib/LLVMInsertCheckPointsOnLoop.so"
LLVM_NOVA_PASS="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/lib/LLVMNova.so"

echo "Enter build directory"
cd bd/src/"$1" || { echo "Directory does not exist"; exit 1; }
echo " Insert CheckPoint and start_collecting"
$LLVM_OPT -load $LLVM_CHECKPOINT_PASS --insert-check-point-on-loop -enable-new-pm=0 -opaque-pointers=0 < ./"$1"_after_compartment_llvm_link.ll > ./"$1"_after_insert_checkpoint.bc

$LLVM_DIS -opaque-pointers=0 "$1"_after_insert_checkpoint.bc -o "$1"_after_insert_checkpoint.ll

echo "Perform LowerSwitch conversion"
$LLVM_OPT -opaque-pointers=0 --lowerswitch -enable-new-pm=0 < "$1"_after_insert_checkpoint.ll > "$1"_after_lower_switch.bc

$LLVM_DIS -opaque-pointers=0 "$1"_after_lower_switch.bc -o "$1"_after_lower_switch.ll

echo "enable data-flow integity"
$LLVM_OPT -load  $LLVM_NOVA_PASS  -enable-new-pm=0  -opaque-pointers=0 -nova --nova-indirect-call-analysis-filepath=./indirectcall.txt --nova-analysis-direct-callfilepath=./direct_call_result.txt -nova-dynamic-collect=DefUseCheck1 "$1"_after_lower_switch.bc > "$1"_enable_data_flow.bc  

$LLVM_DIS -opaque-pointers=0 "$1"_enable_data_flow.bc -o "$1"_enable_data_flow.ll

echo "Insert Dummy Code"
$LLVM_OPT -load  $LLVM_CHECKPOINT_PASS --insert-dummy-code -enable-new-pm=0 -opaque-pointers=0 < "$1"_enable_data_flow.bc > "$1"_after_insert_dummy.bc 
$LLVM_DIS -opaque-pointers=0 "$1"_after_insert_dummy.bc -o "$1"_after_insert_dummy.ll

echo "Copy generated IR files to target directory"
cp "$1"_after_insert_dummy.ll ../../../../pre-analysis16.0/util/output/after_insert_dummy_"$1".ll

cp ./only_called_once_func_backup.txt ../../../../pre-analysis16.0/util/output/only_called_once_func_backup_"$1".txt

echo  "Enter AutoGenerateDummy directory"
cd ../../../../pre-analysis16.0/util/generate_final_hash || { echo "AutoGenerateDummy directory does not exist"; exit 1; }

echo " Run Python script to generate dummy.S"
python3 AutoGenerateDummy.py

echo "Copy dummy.S to target directory"
cp ../output/dummycode.S ../../../measurement-engine/first-measure-in-secure-world/runtime

echo "Process completed!"
cd ../../../embench_test || { echo "embench directory does not exist"; exit 1; }